"""
ViForge Slurm HPC Batch Job Script Generator.
Generates production-grade Slurm batch scripts for multi-node, multi-GPU post-training.
"""

from pathlib import Path
from typing import List, Optional, Union

from viforge.config.schemas import ExperimentManifest
from viforge.utils.logging import logger


class SlurmJobGenerator:
    """
    Generates high-performance batch scripts for Slurm HPC workload managers.
    Supports both Python virtual environments and Apptainer/Singularity container runtimes.
    """

    @classmethod
    def generate_sbatch_script(
        cls,
        manifest: ExperimentManifest,
        config_path: Union[str, Path] = "configs/experiment.yaml",
        job_name: Optional[str] = None,
        nodes: int = 1,
        gpus_per_node: Optional[int] = None,
        cpus_per_task: int = 8,
        time_limit: str = "24:00:00",
        partition: str = "gpu",
        mem_gb: int = 128,
        env_type: str = "venv",
        env_path: Optional[str] = None,
        container_image: Optional[str] = None,
        modules: Optional[List[str]] = None,
        extra_sbatch_flags: Optional[List[str]] = None,
    ) -> str:
        """
        Constructs a complete, executable #SBATCH bash script for multi-GPU training.
        """
        j_name = job_name or f"viforge-{manifest.experiment_id[:24]}"
        num_gpus = gpus_per_node or max(1, manifest.hardware.num_gpus)
        mods = modules or ["cuda/12.1", "nccl"]

        lines = [
            "#!/bin/bash",
            f"#SBATCH --job-name={j_name}",
            f"#SBATCH --nodes={nodes}",
            f"#SBATCH --gpus-per-node={num_gpus}",
            f"#SBATCH --cpus-per-task={cpus_per_task}",
            f"#SBATCH --mem={mem_gb}G",
            f"#SBATCH --time={time_limit}",
            f"#SBATCH --partition={partition}",
            "#SBATCH --output=logs/%x-%j.out",
            "#SBATCH --error=logs/%x-%j.err",
        ]

        if extra_sbatch_flags:
            for flag in extra_sbatch_flags:
                lines.append(f"#SBATCH {flag}")

        lines.extend([
            "",
            "# ViForge Slurm HPC Launch Script",
            "# Auto-generated by ViForge Orchestration Subsystem",
            "set -eo pipefail",
            "",
            "mkdir -p logs checkpoints reports",
            "",
            "# Load HPC environment modules",
        ])

        for m in mods:
            lines.append(f"module load {m} || true")

        lines.extend([
            "",
            "# Network topology and distributed rendezvous configuration",
            "export MASTER_ADDR=$(scontrol show hostnames \"$SLURM_JOB_NODELIST\" 2>/dev/null | head -n 1 || echo \"127.0.0.1\")",
            "export MASTER_PORT=29500",
            "export WORLD_SIZE=$((SLURM_JOB_NUM_NODES * SLURM_GPUS_PER_NODE))",
            "export NCCL_DEBUG=INFO",
            "export PYTHONUNBUFFERED=1",
            "",
        ])

        if env_type == "container" and container_image:
            lines.extend([
                f"# Run within Apptainer / Singularity Container: {container_image}",
                f"CONTAINER_IMG=\"{container_image}\"",
                "srun apptainer exec --nv --bind .:/workspace \"$CONTAINER_IMG\" \\",
                "    torchrun \\",
                "        --nnodes=$SLURM_JOB_NUM_NODES \\",
                "        --nproc_per_node=$SLURM_GPUS_PER_NODE \\",
                "        --rdzv_id=$SLURM_JOB_ID \\",
                "        --rdzv_backend=c10d \\",
                "        --rdzv_endpoint=\"$MASTER_ADDR:$MASTER_PORT\" \\",
                f"        -m viforge.cli.main run {config_path} --live",
            ])
        else:
            activate_cmd = f"source {env_path}/bin/activate" if env_path else "source .venv/bin/activate || true"
            lines.extend([
                "# Activate Python Virtual Environment",
                activate_cmd,
                "",
                "# Execute distributed training across nodes",
                "srun torchrun \\",
                "    --nnodes=$SLURM_JOB_NUM_NODES \\",
                "    --nproc_per_node=$SLURM_GPUS_PER_NODE \\",
                "    --rdzv_id=$SLURM_JOB_ID \\",
                "    --rdzv_backend=c10d \\",
                "    --rdzv_endpoint=\"$MASTER_ADDR:$MASTER_PORT\" \\",
                f"    -m viforge.cli.main run {config_path} --live",
            ])

        lines.extend([
            "",
            "echo \"=== ViForge Slurm Job Finished Successfully: $(date) ===\"",
            "",
        ])

        return "\n".join(lines)

    @classmethod
    def export_sbatch(
        cls,
        manifest: ExperimentManifest,
        output_path: Union[str, Path],
        config_path: Union[str, Path] = "configs/experiment.yaml",
        **kwargs,
    ) -> Path:
        """
        Generates and writes an .sbatch file to disk.
        """
        out_p = Path(output_path)
        out_p.parent.mkdir(parents=True, exist_ok=True)
        content = cls.generate_sbatch_script(manifest, config_path=config_path, **kwargs)
        out_p.write_text(content, encoding="utf-8")
        logger.info(f"Generated Slurm sbatch script at: {out_p}")
        return out_p
